source 'https://rubygems.org'
ruby '2.3.5'

gem 'rubyXL'
gem 'carrierwave'
gem 'cloudinary'
gem 'faker'
gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.5'
gem 'redis'
gem 'similar_text'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'meta-tags'
gem 'sass-rails'
gem 'simple_form'
gem 'snapsvg-rails'
gem 'uglifier'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'binding_of_caller'
end
