meta_product_name: "Papyru"
meta_title: "Papyru · Teaching Platform"
meta_description: "Papyru is a modern platform, developed in Le Wagon Bootcamp Lisbon by three junior developers, that joins students and teachers in a super user-friendly way."
twitter_account: "@gabricanepa"
